try depending on containers >= 0.5.9.1
Travis builds are
failing (https://travis-ci.org/diagrams/geometry/jobs/486903308)
with the error
```
src/Geometry/Trail.hs:234:28: error:
    • Could not deduce (Eq1 Seq) arising from a use of ‘eq1’
      from the context: (Eq1 v, Eq n)
        bound by the instance declaration
        at src/Geometry/Trail.hs:233:10-39
    • In the expression: eq1 s1 s2
      In an equation for ‘==’: (Line s1 _) == (Line s2 _) = eq1 s1 s2
      In the instance declaration for ‘Eq (Line v n)’
```

According to the
[changelog](http://hackage.haskell.org/package/containers-0.6.0.1/changelog),
an `Eq1` instance for `Data.Sequence` was added in `containers-0.5.9.1`.